//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wallet_Main.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wallet_Main.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add an scheduled transaction and the system will take care of your recurring bills and subscriptions..
        /// </summary>
        internal static string AddAutomatedTransactionHint {
            get {
                return ResourceManager.GetString("AddAutomatedTransactionHint", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Budget.
        /// </summary>
        internal static string AddBudget {
            get {
                return ResourceManager.GetString("AddBudget", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Budgets to keep an eye on your expenses.
        /// </summary>
        internal static string AddBudgets {
            get {
                return ResourceManager.GetString("AddBudgets", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add First Transaction.
        /// </summary>
        internal static string AddFirstTransaction {
            get {
                return ResourceManager.GetString("AddFirstTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Set your first budget to control your spending..
        /// </summary>
        internal static string AddYourFirstBudget {
            get {
                return ResourceManager.GetString("AddYourFirstBudget", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu and.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 📁 App Data.
        /// </summary>
        internal static string AppData {
            get {
                return ResourceManager.GetString("AppData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Balance Projection.
        /// </summary>
        internal static string BalanceProjection {
            get {
                return ResourceManager.GetString("BalanceProjection", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Goal.
        /// </summary>
        internal static string BudgetGoal {
            get {
                return ResourceManager.GetString("BudgetGoal", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose Category.
        /// </summary>
        internal static string ChooseCategory {
            get {
                return ResourceManager.GetString("ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose Currency.
        /// </summary>
        internal static string ChooseCurrency {
            get {
                return ResourceManager.GetString("ChooseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose file with data.
        /// </summary>
        internal static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose Frequency.
        /// </summary>
        internal static string ChooseFrequency {
            get {
                return ResourceManager.GetString("ChooseFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Collecting Data....
        /// </summary>
        internal static string CollectingData {
            get {
                return ResourceManager.GetString("CollectingData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Congratulations!.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 💱 Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Daily.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Date.
        /// </summary>
        internal static string Date_Time {
            get {
                return ResourceManager.GetString("Date_Time", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu days Left to unlock this content.
        /// </summary>
        internal static string DaysLeft {
            get {
                return ResourceManager.GetString("DaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter new category name.
        /// </summary>
        internal static string EnterCategoryName {
            get {
                return ResourceManager.GetString("EnterCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter The Amount.
        /// </summary>
        internal static string EnterTheAmount {
            get {
                return ResourceManager.GetString("EnterTheAmount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expense.
        /// </summary>
        internal static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expense.
        /// </summary>
        internal static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expense Structure.
        /// </summary>
        internal static string ExpenseStructure {
            get {
                return ResourceManager.GetString("ExpenseStructure", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Frequency.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hello!.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Icon.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Import Data.
        /// </summary>
        internal static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Income.
        /// </summary>
        internal static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Income.
        /// </summary>
        internal static string Incomes {
            get {
                return ResourceManager.GetString("Incomes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Main Page.
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Monthly.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Monthly Balance .
        /// </summary>
        internal static string MonthlyBalance {
            get {
                return ResourceManager.GetString("MonthlyBalance", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Monthly Limit.
        /// </summary>
        internal static string MonthlyLimit {
            get {
                return ResourceManager.GetString("MonthlyLimit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Month Summary.
        /// </summary>
        internal static string MonthSummary {
            get {
                return ResourceManager.GetString("MonthSummary", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New Budget.
        /// </summary>
        internal static string NewBudget {
            get {
                return ResourceManager.GetString("NewBudget", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu new categories.
        /// </summary>
        internal static string NewCategories {
            get {
                return ResourceManager.GetString("NewCategories", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New Category.
        /// </summary>
        internal static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No Scheduled Transaction .
        /// </summary>
        internal static string NoAutomatedtransaction {
            get {
                return ResourceManager.GetString("NoAutomatedtransaction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No Budets.
        /// </summary>
        internal static string NoBudgets {
            get {
                return ResourceManager.GetString("NoBudgets", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No data to show.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add transactions from previous months to unlock.
        /// </summary>
        internal static string PreviousMonths {
            get {
                return ResourceManager.GetString("PreviousMonths", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Recent Transactions.
        /// </summary>
        internal static string RecentOperations {
            get {
                return ResourceManager.GetString("RecentOperations", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Recurring Payment.
        /// </summary>
        internal static string RecurringPayment {
            get {
                return ResourceManager.GetString("RecurringPayment", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Restart App for the change to work properly.
        /// </summary>
        internal static string RestartApp {
            get {
                return ResourceManager.GetString("RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save Data.
        /// </summary>
        internal static string SaveData {
            get {
                return ResourceManager.GetString("SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save Transaction.
        /// </summary>
        internal static string SaveTransaction {
            get {
                return ResourceManager.GetString("SaveTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Scheduled Transaction.
        /// </summary>
        internal static string ScheduledTransaction {
            get {
                return ResourceManager.GetString("ScheduledTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add transaction today and once a  day,week ....
        /// </summary>
        internal static string ScheduledTransactionDescribtion {
            get {
                return ResourceManager.GetString("ScheduledTransactionDescribtion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Scheduled Transactions.
        /// </summary>
        internal static string ScheduledTransactions {
            get {
                return ResourceManager.GetString("ScheduledTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu See what your month looked like.
        /// </summary>
        internal static string SeeHowYourMothLoo {
            get {
                return ResourceManager.GetString("SeeHowYourMothLoo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Spent.
        /// </summary>
        internal static string Spent {
            get {
                return ResourceManager.GetString("Spent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu To unlock advanced statistical analysis and trends, use the app actively for at least 3 months..
        /// </summary>
        internal static string StatisticPageEmpty {
            get {
                return ResourceManager.GetString("StatisticPageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Success! Added.
        /// </summary>
        internal static string SuccessAdded1 {
            get {
                return ResourceManager.GetString("SuccessAdded1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu new transactions.
        /// </summary>
        internal static string SuccessAdded2 {
            get {
                return ResourceManager.GetString("SuccessAdded2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu In this month you managed to save.
        /// </summary>
        internal static string SummaryBalance {
            get {
                return ResourceManager.GetString("SummaryBalance", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu In this month you spent more than you earnt by .
        /// </summary>
        internal static string SummaryBalanceOnMinus {
            get {
                return ResourceManager.GetString("SummaryBalanceOnMinus", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Budget Exceeded.
        /// </summary>
        internal static string Summarybudgetexceeded {
            get {
                return ResourceManager.GetString("Summarybudgetexceeded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Expense Categorie.
        /// </summary>
        internal static string SummaryExpenseStructure {
            get {
                return ResourceManager.GetString("SummaryExpenseStructure", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu See Where The Money Goes.
        /// </summary>
        internal static string SummaryExpenseStructureDescription {
            get {
                return ResourceManager.GetString("SummaryExpenseStructureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Goal Achieved.
        /// </summary>
        internal static string SummaryGoalAchieved {
            get {
                return ResourceManager.GetString("SummaryGoalAchieved", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Go Back To Your Wallet.
        /// </summary>
        internal static string SummaryGoBackToWallet {
            get {
                return ResourceManager.GetString("SummaryGoBackToWallet", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You have used our app for.
        /// </summary>
        internal static string SummaryHowLongUsesApp {
            get {
                return ResourceManager.GetString("SummaryHowLongUsesApp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Let see how it went with your budget!.
        /// </summary>
        internal static string SummaryLetSee {
            get {
                return ResourceManager.GetString("SummaryLetSee", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Summary of.
        /// </summary>
        internal static string SummaryMonth {
            get {
                return ResourceManager.GetString("SummaryMonth", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Months in a row of saving.
        /// </summary>
        internal static string SummaryMonthsInRow {
            get {
                return ResourceManager.GetString("SummaryMonthsInRow", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You have no expenses this month..
        /// </summary>
        internal static string SummaryNoExpenses {
            get {
                return ResourceManager.GetString("SummaryNoExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu How did you achieve this?.
        /// </summary>
        internal static string SummaryNoExpenses2 {
            get {
                return ResourceManager.GetString("SummaryNoExpenses2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu It is more than on a previous month by .
        /// </summary>
        internal static string SummarySavedMoreThenBefore {
            get {
                return ResourceManager.GetString("SummarySavedMoreThenBefore", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Savings Streak.
        /// </summary>
        internal static string SummarySavingsStreak {
            get {
                return ResourceManager.GetString("SummarySavingsStreak", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 🎉 Your Month In Numbers.
        /// </summary>
        internal static string SummaryYourMonth {
            get {
                return ResourceManager.GetString("SummaryYourMonth", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tame your expenses.
        /// </summary>
        internal static string TameYourExpenses {
            get {
                return ResourceManager.GetString("TameYourExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu e.g. 7-eleven groceries.
        /// </summary>
        internal static string TitleExample {
            get {
                return ResourceManager.GetString("TitleExample", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu To unlock balance chart add at least one transaction.
        /// </summary>
        internal static string ToUnlockChart {
            get {
                return ResourceManager.GetString("ToUnlockChart", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Transaction.
        /// </summary>
        internal static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Transaction Details.
        /// </summary>
        internal static string TransactionDetails {
            get {
                return ResourceManager.GetString("TransactionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Upcoming Transactions.
        /// </summary>
        internal static string UpcomingTransactions {
            get {
                return ResourceManager.GetString("UpcomingTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Weekly.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wild Wallet.
        /// </summary>
        internal static string WildWallet {
            get {
                return ResourceManager.GetString("WildWallet", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wild Wallet Wrapped.
        /// </summary>
        internal static string Wrapped {
            get {
                return ResourceManager.GetString("Wrapped", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Yearly.
        /// </summary>
        internal static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your Budgets.
        /// </summary>
        internal static string YourBudgets {
            get {
                return ResourceManager.GetString("YourBudgets", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu A Penny Saved Is A Penny Earned .
        /// </summary>
        internal static string YourBudgetsDescription {
            get {
                return ResourceManager.GetString("YourBudgetsDescription", resourceCulture);
            }
        }
    }
}
